AWSTemplateFormatVersion: 2010-09-09
Description: >-
  AWS CloudFormation Sample Template Create a load balanced Jenkins CI server
  with Docker installed. The application is using CloudWatch logs **WARNING**
  This template creates an Amazon EC2 instance in an Autoscaling group. You will
  be billed for the AWS resources used if you create a stack from this template.
Parameters:
  VpcName:
    Type: AWS::EC2::VPC::Id
    Description: VPC Identifier
  SubnetID:
    Type: AWS::EC2::Subnet::Id
    Description: Subnet to deploy EC2 instance into

  KeyName:
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instance
    Type: 'AWS::EC2::KeyPair::KeyName'
    ConstraintDescription: must be the name of an existing EC2 KeyPair.
  InstanceType:
    Description: WebServer EC2 instance type
    Type: String
    Default: t2.medium
    AllowedValues:
      - t1.micro
      - t2.micro
      - t2.small
      - t2.medium
      - m3.medium
      - m3.large
      - m3.xlarge
      - m3.2xlarge
      - c3.large
      - c3.xlarge
      - c3.2xlarge
      - c3.4xlarge
      - c3.8xlarge
      - c4.large
      - c4.xlarge
      - c4.2xlarge
      - c4.4xlarge
      - c4.8xlarge
      - r3.large
      - r3.xlarge
      - r3.2xlarge
      - r3.4xlarge
      - r3.8xlarge
      - i2.xlarge
      - i2.2xlarge
      - i2.4xlarge
      - i2.8xlarge
      - hi1.4xlarge
      - hs1.8xlarge
      - cr1.8xlarge
      - cc2.8xlarge
    ConstraintDescription: must be a valid EC2 instance type.
  SSHLocation:
    Description: The IP address range that can be used to SSH to the EC2 instances
    Type: String
    MinLength: '9'
    MaxLength: '18'
    Default: 0.0.0.0/0
    AllowedPattern: '(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})'
    ConstraintDescription: must be a valid IP CIDR range of the form x.x.x.x/x.
  group:
    Description: The group name of environment
    Type: String
    MinLength: '6'
    MaxLength: '18'

Mappings:
  AWSInstanceType2Arch:
    t1.micro:
      Arch: PV64
    t2.micro:
      Arch: HVM64
    t2.small:
      Arch: HVM64
    t2.medium:
      Arch: HVM64
    m3.medium:
      Arch: HVM64
    m3.large:
      Arch: HVM64
    m3.xlarge:
      Arch: HVM64
    m3.2xlarge:
      Arch: HVM64
    c3.large:
      Arch: HVM64
    c3.xlarge:
      Arch: HVM64
    c3.2xlarge:
      Arch: HVM64
    c3.4xlarge:
      Arch: HVM64
    c3.8xlarge:
      Arch: HVM64
    c4.large:
      Arch: HVM64
    c4.xlarge:
      Arch: HVM64
    c4.2xlarge:
      Arch: HVM64
    c4.4xlarge:
      Arch: HVM64
    c4.8xlarge:
      Arch: HVM64
    r3.large:
      Arch: HVM64
    r3.xlarge:
      Arch: HVM64
    r3.2xlarge:
      Arch: HVM64
    r3.4xlarge:
      Arch: HVM64
    r3.8xlarge:
      Arch: HVM64
    i2.xlarge:
      Arch: HVM64
    i2.2xlarge:
      Arch: HVM64
    i2.4xlarge:
      Arch: HVM64
    i2.8xlarge:
      Arch: HVM64
    hi1.4xlarge:
      Arch: HVM64
    hs1.8xlarge:
      Arch: HVM64
    cr1.8xlarge:
      Arch: HVM64
    cc2.8xlarge:
      Arch: HVM64
  AWSRegionArch2AMI:
    us-east-1:
      PV64: ami-f0ea638a
      HVM64: ami-55ef662f
    us-west-2:
      PV64: ami-da4694a2
      HVM64: ami-bf4193c7
    us-west-1:
      PV64: ami-3b1e265b
      HVM64: ami-a51f27c5
    eu-west-1:
      PV64: ami-889622f1
      HVM64: ami-1a962263
    eu-central-1:
      PV64: ami-2928ab46
      HVM64: ami-bf2ba8d0
    ap-northeast-1:
      PV64: ami-99982aff
      HVM64: ami-da9e2cbc
    ap-southeast-1:
      PV64: ami-3f3d6a5c
      HVM64: ami-c63d6aa5
    ap-southeast-2:
      PV64: ami-3249a250
      HVM64: ami-ff4ea59d
    sa-east-1:
      PV64: ami-b96c29d5
      HVM64: ami-286f2a44
Resources:
  JenkinsRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/AmazonEC2ContainerServiceFullAccess'
        - 'arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryFullAccess'
        - 'arn:aws:iam::aws:policy/AmazonS3FullAccess'
      Path: /
      Policies:
        - PolicyName: JenkinsRolePolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - 'logs:*'
                Resource:
                  - 'arn:aws:logs:*:*:*'
              - Effect: Allow
                Action: 'ecs:*'
                Resource: '*'
  JenkinsInstanceProfile:
    Type: 'AWS::IAM::InstanceProfile'
    Properties:
      Path: /
      Roles:
        - !Ref JenkinsRole
  
  JenkinsInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !FindInMap 
        - AWSRegionArch2AMI
        - !Ref 'AWS::Region'
        - !FindInMap 
          - AWSInstanceType2Arch
          - !Ref InstanceType
          - Arch
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyName
      IamInstanceProfile: !Ref JenkinsInstanceProfile      
      BlockDeviceMappings:
        -
          DeviceName: /dev/xvda
          Ebs:
            VolumeSize: 100
            VolumeType: 'gp2'
      NetworkInterfaces: 
        - AssociatePublicIpAddress: "true"
          DeviceIndex: "0"
          GroupSet: 
            - !Ref InstanceSecurityGroup
          SubnetId: !Ref SubnetID
      UserData: !Base64 
        'Fn::Join':
          - ''
          - - |
              #!/bin/bash -xe
            - |
              yum update -y
            - |+

            - |
              yum remove -y java-1.7.0 && yum install -y java-1.8.0-openjdk.x86_64 docker git httpd-tools jq
            - |+
              # Disable ssl verification for cobis tfs git, becuase cert issue
            - |
              echo '[http "https://192.188.45.137/"]' >> /var/lib/jenkins/.gitconfig
            - |
              echo 'sslVerify=false' >> /var/lib/jenkins/.gitconfig
            - |+

              # Install Jenkins
            - >
              wget -O /etc/yum.repos.d/jenkins.repo
              http://pkg.jenkins-ci.org/redhat/jenkins.repo
            - |
              rpm --import http://pkg.jenkins-ci.org/redhat/jenkins-ci.org.key
            - |
              useradd -d /var/lib/jenkins jenkins
            - |
              yum install -y jenkins
            - |
              # Add Jenkins user to Docker group
            - |
              usermod -a -G docker jenkins
            - |
              # Add jenkins user as sudo user without password
            - |
              cp /etc/sudoers.d/cloud-init /etc/sudoers.d/jenkins && sed -i 's/ec2-user/jenkins/g' /etc/sudoers.d/jenkins
            - |
              service jenkins start
            - |
              chkconfig jenkins on
            - |
              # Wait 30 seconds to allow Jenkins to startup
            - |
              echo "Waiting 30 seconds for Jenkins to start....."
            - |
              sleep 30
            - |
              # Install the required plugins
            - |
              cd /var/lib/jenkins/plugins
            - |
              curl -O -L https://updates.jenkins-ci.org/latest/token-macro.hpi
            - >
              curl -O -L
              https://updates.jenkins-ci.org/latest/docker-build-publish.hpi
            - |
              curl -O -L https://updates.jenkins-ci.org/latest/multiple-scms.hpi
            - |
              curl -O -L https://updates.jenkins-ci.org/latest/github-api.hpi
            - |
              curl -O -L https://updates.jenkins-ci.org/latest/scm-api.hpi
            - |
              curl -O -L https://updates.jenkins-ci.org/latest/git-client.hpi
            - |
              curl -O -L https://updates.jenkins-ci.org/latest/github.hpi
            - |
              curl -O -L https://updates.jenkins-ci.org/latest/git.hpi
            - |
              curl -O -L https://updates.jenkins-ci.org/latest/jackson2-api.hpi
            - |
              curl -O -L https://updates.jenkins-ci.org/latest/variant.hpi
            - |
              curl -O -L https://updates.jenkins-ci.org/latest/jira.hpi
            - |
              curl -O -L https://updates.jenkins-ci.org/latest/mailer.hpi
            - |
              curl -O -L https://updates.jenkins-ci.org/latest/structs.hpi
            - |
              curl -O -L https://updates.jenkins-ci.org/latest/handy-uri-templates-2-api.hpi
            - |
              curl -O -L https://updates.jenkins-ci.org/latest/ace-editor.hpi
            - |
              curl -O -L https://updates.jenkins-ci.org/latest/jquery-detached.hpi
            - |
              curl -O -L https://updates.jenkins-ci.org/latest/junit.hpi
            - |
              curl -O -L https://updates.jenkins-ci.org/latest/ssh-credentials.hpi
            - |
              curl -O -L https://updates.jenkins-ci.org/latest/apache-httpcomponents-client-4-api.hpi
            - |
              curl -O -L https://updates.jenkins-ci.org/latest/docker-commons.hpi
            - |
              curl -O -L https://updates.jenkins-ci.org/latest/authentication-tokens.hpi
            - |
              curl -O -L https://updates.jenkins-ci.org/latest/jsch.hpi
            - |
              curl -O -L https://updates.jenkins-ci.org/latest/mercurial.hpi
            - |
              curl -O -L https://updates.jenkins-ci.org/latest/sse-gateway.hpi
            - |
              curl -O -L https://updates.jenkins-ci.org/latest/matrix-project.hpi
            - |
              curl -O -L https://updates.jenkins-ci.org/latest/script-security.hpi
            - |
              curl -O -L https://updates.jenkins-ci.org/latest/cloudbees-bitbucket-branch-source.hpi
            - |
              curl -O -L https://updates.jenkins-ci.org/latest/cloudbees-folder.hpi
            - |
              curl -O -L https://updates.jenkins-ci.org/latest/workflow-api.hpi
            - |
              curl -O -L https://updates.jenkins-ci.org/latest/workflow-scm-step.hpi
            - |
              curl -O -L https://updates.jenkins-ci.org/latest/workflow-support.hpi
            - |
              curl -O -L https://updates.jenkins-ci.org/latest/workflow-step-api.hpi
            - |
              curl -O -L https://updates.jenkins-ci.org/latest/workflow-job.hpi
            - |
              curl -O -L https://updates.jenkins-ci.org/latest/display-url-api.hpi
            - |
              curl -O -L https://updates.jenkins-ci.org/latest/workflow-cps.hpi
            - |
              curl -O -L https://updates.jenkins-ci.org/latest/favorite.hpi
            - |
              curl -O -L https://updates.jenkins-ci.org/latest/pubsub-light.hpi
            - |
              curl -O -L https://updates.jenkins-ci.org/latest/credentials.hpi
            - |
              curl -O -L https://updates.jenkins-ci.org/latest/branch-api.hpi
            - |
              curl -O -L https://updates.jenkins-ci.org/latest/workflow-multibranch.hpi
            - |
              curl -O -L https://updates.jenkins-ci.org/latest/htmlpublisher.hpi
            - |
              curl -O -L https://updates.jenkins-ci.org/latest/pipeline-build-step.hpi
            - |
              curl -O -L https://updates.jenkins-ci.org/latest/plain-credentials.hpi
            - |
              curl -O -L https://updates.jenkins-ci.org/latest/github-branch-source.hpi
            - |
              curl -O -L https://updates.jenkins-ci.org/latest/pipeline-graph-analysis.hpi
            - |
              curl -O -L https://updates.jenkins-ci.org/latest/pipeline-stage-step.hpi
            - |
              curl -O -L https://updates.jenkins-ci.org/latest/pipeline-input-step.hpi
            - |
              curl -O -L https://updates.jenkins-ci.org/latest/workflow-durable-task-step.hpi
            - |
              curl -O -L https://updates.jenkins-ci.org/latest/pipeline-model-definition.hpi
            - |
              curl -O -L https://updates.jenkins-ci.org/latest/pipeline-stage-tags-metadata.hpi
            - |
              curl -O -L https://updates.jenkins-ci.org/latest/plain-credentials.hpi
            - |
              curl -O -L https://updates.jenkins-ci.org/latest/credentials-binding.hpi
            - |
              curl -O -L https://updates.jenkins-ci.org/latest/durable-task.hpi
            - |
              curl -O -L https://updates.jenkins-ci.org/latest/workflow-cps-global-lib.hpi
            - |
              curl -O -L https://updates.jenkins-ci.org/latest/workflow-basic-steps.hpi
            - |
              curl -O -L https://updates.jenkins-ci.org/latest/git-server.hpi
            - |
              curl -O -L https://updates.jenkins-ci.org/latest/pipeline-model-api.hpi
            - |
              curl -O -L https://updates.jenkins-ci.org/latest/pipeline-model-extensions.hpi
            - |
              curl -O -L https://updates.jenkins-ci.org/latest/docker-workflow.hpi
            - |
              curl -O -L https://updates.jenkins-ci.org/latest/pipeline-model-declarative-agent.hpi
            - |
              curl -O -L https://updates.jenkins-ci.org/latest/pipeline-milestone-step.hpi
            - |
              curl -O -L https://updates.jenkins-ci.org/latest/blueocean.hpi
            - |
              curl -O -L https://updates.jenkins-ci.org/latest/blueocean-i18n.hpi
            - |
              curl -O -L https://updates.jenkins-ci.org/latest/blueocean-git-pipeline.hpi
            - |
              curl -O -L https://updates.jenkins-ci.org/latest/blueocean-core-js.hpi
            - |
              curl -O -L https://updates.jenkins-ci.org/latest/blueocean-rest-impl.hpi
            - |
              curl -O -L https://updates.jenkins-ci.org/latest/blueocean-config.hpi
            - |
              curl -O -L https://updates.jenkins-ci.org/latest/blueocean-events.hpi
            - |
              curl -O -L https://updates.jenkins-ci.org/latest/blueocean-dashboard.hpi
            - |
              curl -O -L https://updates.jenkins-ci.org/latest/blueocean-autofavorite.hpi
            - |
              curl -O -L https://updates.jenkins-ci.org/latest/blueocean-pipeline-api-impl.hpi
            - |
              curl -O -L https://updates.jenkins-ci.org/latest/blueocean-commons.hpi
            - |
              curl -O -L https://updates.jenkins-ci.org/latest/blueocean-pipeline-editor.hpi
            - |
              curl -O -L https://updates.jenkins-ci.org/latest/blueocean-pipeline-scm-api.hpi
            - |
              curl -O -L https://updates.jenkins-ci.org/latest/blueocean-bitbucket-pipeline.hpi
            - |
              curl -O -L https://updates.jenkins-ci.org/latest/blueocean-personalization.hpi
            - |
              curl -O -L https://updates.jenkins-ci.org/latest/blueocean-rest.hpi
            - |
              curl -O -L https://updates.jenkins-ci.org/latest/blueocean-github-pipeline.hpi
            - |
              curl -O -L https://updates.jenkins-ci.org/latest/jenkins-design-language.hpi
            - |
              curl -O -L https://updates.jenkins-ci.org/latest/blueocean-jira.hpi
            - |
              curl -O -L https://updates.jenkins-ci.org/latest/blueocean-display-url.hpi
            - |
              curl -O -L https://updates.jenkins-ci.org/latest/blueocean-jwt.hpi
            - |
              curl -O -L https://updates.jenkins-ci.org/latest/blueocean-web.hpi
            - |
              chown jenkins:jenkins *.hpi
            - |
              # Restarting Jenkins
            - |
              service jenkins restart
            - |+

              # Install go and s5cmd
            - |
              curl -O -L https://dl.google.com/go/go1.11.5.linux-amd64.tar.gz
            - |
              tar -C /usr/local -xzf go1.11.5.linux-amd64.tar.gz
            - |
              var1=$(grep -i "PATH=" /root/.bash_profile)
            - |
              sed -i 's;^PATH=.*;'"$var1"':/usr/local/go/bin;' /root/.bash_profile
            - |
              var1=$(grep -i "PATH=" /var/lib/jenkins/.bash_profile)
            - |
              sed -i 's;^PATH=.*;'"$var1"':/usr/local/go/bin;' /var/lib/jenkins/.bash_profile
            - |
              su jenkins -c "cd && /usr/local/go/bin/go get -u github.com/peakgames/s5cmd"
            - |+

              # enable docker server
            - |
              sudo chkconfig docker on
            - |+

              # Install Ruby and mustache
            - |
              gem install mustache
            - |+            
      Tags:                                      # Tags are an example of a sequence of mappings in YAML,
        -                                        # each key/value pair is separated by a hyphen
          Key: Name
          Value: !Join [ '-', ['Jenkins', !Ref group] ]
        -
          Key: Environment
          Value: Development  
        -
          Key: group
          Value: !Ref group  

  InstanceSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Enable SSH access and HTTP from anywhere
      VpcId: !Ref VpcName      
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: !Ref SSHLocation
        - IpProtocol: tcp
          FromPort: '80'
          ToPort: '80'
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: '8080'
          ToPort: '8080'
          CidrIp: 0.0.0.0/0
